@Library('saao-shared-library') _

pipeline {
  agent any

  stages {
    stage('Run tests') {
      agent {
        dockerfile {
          filename 'Dockerfile'
          dir 'jenkins'
          args '-v imephu-venv:/.cache/pypoetry -u 0:0'
        }
      }

      steps {
        script {
          sh 'poetry add --group=dev allure-pytest black mypy pytest ruff'
          sh 'poetry install'
          def success = saao.runPythonTests(
            'black': ['src', 'tests'],
            'mypy': ['src', 'tests'],
            'pytest': ['tests'],
            'ruff': ['src', 'tests'],
            'usePoetry': true
          )
          if (!success) {
            error("Tests failed.")
          }
        }
      }
    }
  }

  post {
    always {
      script {
        saao.generatePythonTestReports()
      }
      cleanWs()
    }
  }
}
