@Library('saao-shared-library') _

pipeline {
  agent none

  stages {
    stage('Run tests') {
      agent {
        dockerfile {
          filename 'Dockerfile'
          dir 'jenkins/testing'
          args '-v imephu-venv:/venv -u 0:0'
        }
      }

      steps {
        sh 'poetry export -f requirements.txt --with dev --output requirements.txt'
        sh 'pip install -r requirements.txt'
        script {
          saao.runTests(
            'black': ['src', 'tests'],
            'mypy': ['src', 'tests'],
            'pytest': ['tests'],
            'ruff':['src', 'tests']
          )
        }
      }
    }
  }

  post {
    always {
      script {
        saao.generatePythonTestReports()
      }
    }
  }
}
