@Library('saao-shared-library') _

pipeline {
  agent any

  stages {
    stage('Run tests') {
      agent {
        dockerfile {
          filename 'Dockerfile'
          dir 'jenkins'
          args '-v imephu-venv:/venv -u 0:0'
        }
      }

      steps {
        sh 'poetry export --without-hashes -f requirements.txt --with dev --output requirements.txt'
        sh 'pip install -r requirements.txt'
        script {
          saao.runPythonTests(
            'black': ['src', 'tests'],
            'mypy': ['src', 'tests'],
            'pytest': ['tests'],
            'ruff': ['src', 'tests']
          )
        }
      }
    }
  }

  post {
    always {
      script {
        saao.generatePythonTestReports()
      }
    }
  }
}
