pipeline {
  agent {
    dockerfile {
      filename 'Dockerfile'
      dir 'jenkins'
      args '-v imephu-venv:/.cache/pypoetry -u 0:0'
    }
  }

  environment {
    PYPI_CREDENTIALS = credentials('pypi-dev-credentials')
  }

  stages {
    stage('Deploy') {
      steps {
        sh '''
        poetry config repositories/dev http://pypi.cape.saao.ac.za:8080/
        poetry build
        poetry publish -r dev --username $PYPI_CREDENTIALS_USR --password $PYPI_CREDENTIALS_PSW
        '''
      }
    }
  }
}
